### PR TITLE
corrected javascript url

### PR DESCRIPTION
**Pull request by MikeLeber117**
This was a request from Ryan Olsen and fixes issue https://github.com/OpenF2/iOS-Container/issues/3

### CODE REVIEW

**Comment by timburcham** [comment]
Hey there, could a fellow @OpenF2/owners or @OpenF2/contributors take a look at this and provide a peer review?

**Comment by brianbaker** [comment]
I think GitHub frowns (and may block) references to raw content.  I think it would be better to use F2 sourced from cdnjs: https://cdnjs.cloudflare.com/ajax/libs/F2/1.4.0/f2.min.js assuming that the `1.4.0` version suits your needs.

**Comment by MikeLeber117** [comment]
I will need to find out from Ryan Olsen if we can use that one.

**Comment by MikeLeber117** [comment]
Ok, made a change. Ryan Olsen was unsure if using 1.4.0 would cause any problems. @brianbaker, if you are fine with that version we should be able to merge this.

**Comment by brianbaker** [comment]
I'm certainly fine with it - its the latest stable release so don't know why we would want examples that use outdated versions.

**Pull request merged**
